// Consumes explicit PortariaCall AMI UserEvents. Unknown access bindings are ignored.
package main
import("bufio";"bytes";"crypto/sha256";"crypto/tls";"encoding/hex";"encoding/json";"fmt";"io";"log";"net";"net/http";"os";"path/filepath";"strings";"time")
type Binding struct{Company string `json:"company_id"`;Condo string `json:"condo_id"`}
type Event struct{Company string `json:"company_id"`;Condo string `json:"condo_id"`;Access string `json:"access_id"`;Call string `json:"call_id"`;Kind string `json:"kind"`}
type Bridge struct{bindings map[string]Binding;spool,api,key string;client *http.Client}
func main(){b:=&Bridge{spool:os.Getenv("EVENT_SPOOL"),api:os.Getenv("API_URL"),key:os.Getenv("INTERNAL_KEY"),client:&http.Client{Timeout:10*time.Second}};if b.spool==""{b.spool="/var/lib/portaria-telephony"};if b.api==""||b.key==""||os.Getenv("AMI_ADDRESS")==""||os.Getenv("AMI_USERNAME")==""||os.Getenv("AMI_SECRET")==""{log.Fatal("Configure API_URL, INTERNAL_KEY, AMI_ADDRESS, AMI_USERNAME and AMI_SECRET")};if err:=json.Unmarshal([]byte(os.Getenv("ACCESS_BINDINGS")),&b.bindings);err!=nil{log.Fatal("ACCESS_BINDINGS must be a JSON map of real access UUIDs to company/condo bindings")};if err:=os.MkdirAll(b.spool,0700);err!=nil{log.Fatal(err)};go func(){ticker:=time.NewTicker(2*time.Second);defer ticker.Stop();for range ticker.C{b.flush()}}();for{if err:=b.listen();err!=nil{log.Printf("AMI unavailable: %v",err)};time.Sleep(5*time.Second)}}
func(b *Bridge)listen()error{address:=os.Getenv("AMI_ADDRESS");var conn net.Conn;var err error;if os.Getenv("AMI_TLS")=="true"{host,_,e:=net.SplitHostPort(address);if e!=nil{return e};conn,err=tls.DialWithDialer(&net.Dialer{Timeout:10*time.Second},"tcp",address,&tls.Config{ServerName:host,MinVersion:tls.VersionTLS12})}else{conn,err=net.DialTimeout("tcp",address,10*time.Second)};if err!=nil{return err};defer conn.Close();for _,v:=range []string{os.Getenv("AMI_USERNAME"),os.Getenv("AMI_SECRET")}{if strings.ContainsAny(v,"\r\n"){return fmt.Errorf("invalid AMI credential format")}};_,err=fmt.Fprintf(conn,"Action: Login\r\nUsername: %s\r\nSecret: %s\r\nEvents: on\r\n\r\n",os.Getenv("AMI_USERNAME"),os.Getenv("AMI_SECRET"));if err!=nil{return err};scanner:=bufio.NewScanner(conn);scanner.Buffer(make([]byte,4096),131072);event:=map[string]string{};for scanner.Scan(){line:=strings.TrimSpace(scanner.Text());if line==""{if event["response"]=="Error"{return fmt.Errorf("AMI authentication rejected")};if e,ok:=b.translate(event);ok{if err:=b.persist(e);err!=nil{return err}};event=map[string]string{};continue};parts:=strings.SplitN(line,":",2);if len(parts)==2{event[strings.ToLower(strings.TrimSpace(parts[0]))]=strings.TrimSpace(parts[1])}};return scanner.Err()}
func(b *Bridge)translate(raw map[string]string)(Event,bool){if raw["event"]!="UserEvent"||raw["userevent"]!="PortariaCall"{return Event{},false};bind,ok:=b.bindings[raw["access"]];if !ok||bind.Company==""||bind.Condo==""{return Event{},false};kind:=raw["kind"];if kind!="ringing"&&kind!="answered"&&kind!="ended"&&kind!="missed"{return Event{},false};id:=raw["callid"];if id==""||len(id)>100{return Event{},false};return Event{Company:bind.Company,Condo:bind.Condo,Access:raw["access"],Call:id,Kind:kind},true}
func(b *Bridge)persist(e Event)error{data,err:=json.Marshal(e);if err!=nil{return err};sum:=sha256.Sum256([]byte(e.Company+":"+e.Call+":"+e.Kind));path:=filepath.Join(b.spool,hex.EncodeToString(sum[:])+".json");tmp:=path+".tmp";f,err:=os.OpenFile(tmp,os.O_WRONLY|os.O_CREATE|os.O_TRUNC,0600);if err!=nil{return err};if _,err=f.Write(data);err!=nil{f.Close();return err};if err=f.Sync();err!=nil{f.Close();return err};if err=f.Close();err!=nil{return err};return os.Rename(tmp,path)}
func(b *Bridge)flush(){files,err:=os.ReadDir(b.spool);if err!=nil{return};for _,f:=range files{if f.IsDir()||!strings.HasSuffix(f.Name(),".json"){continue};path:=filepath.Join(b.spool,f.Name());data,err:=os.ReadFile(path);if err!=nil||len(data)>16384{continue};req,err:=http.NewRequest("POST",strings.TrimRight(b.api,"/")+"/internal/telephony/events",bytes.NewReader(data));if err!=nil{continue};req.Header.Set("Content-Type","application/json");req.Header.Set("X-Service-Key",b.key);resp,err:=b.client.Do(req);if err!=nil{continue};_,_=io.Copy(io.Discard,io.LimitReader(resp.Body,4096));resp.Body.Close();if resp.StatusCode>=200&&resp.StatusCode<300{if err=os.Remove(path);err!=nil{log.Print("could not remove acknowledged event; API deduplication will prevent duplicate effects")}}}}
