'use client';
import { useEffect,useRef,useState,useCallback,type FormEvent,type CSSProperties } from 'react';
import Keycloak from 'keycloak-js';
import { ArrowUpRight,ArrowRight,Building2,Check,CheckCircle2,ChevronDown,ChevronRight,Clock3,DoorOpen,Ellipsis,Globe2,Headphones,LayoutDashboard,Link2,Loader2,LockKeyhole,LogIn,LogOut,Menu,MessageCircle,Palette,Plus,Search,Settings2,ShieldCheck,Ticket,Users,Video,X,Activity,Car,KeyRound,Radio,Copy,AlertCircle,ExternalLink,RefreshCw,Smartphone,HelpCircle } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { CameraPlayer,TelephonyPanel } from './live-media';
import WhatsAppPanel from './whatsapp-panel';
type Row=Record<string,any>;
type View='overview'|'companies'|'central'|'condos'|'people'|'invitations'|'access-points'|'devices'|'credentials'|'vehicles'|'events'|'brand'|'integrations'|'memberships'|'units'|'cameras'|'intercoms'|'incidents';
const titles:Record<View,string>={overview:'Visão geral',companies:'Clientes',central:'Central de atendimento',condos:'Condomínios',people:'Pessoas',invitations:'Convites', 'access-points':'Pontos de acesso',devices:'Equipamentos',credentials:'Credenciais',vehicles:'Veículos',events:'Histórico de acessos',brand:'White label',integrations:'Integrações',memberships:'Equipe e permissões',units:'Unidades',cameras:'Câmeras',intercoms:'Interfonia',incidents:'Ocorrências'};
const labels:Record<string,string>={draft:'Em configuração',active:'Ativo',suspended:'Suspenso',cancelled:'Cancelado',used:'Utilizado',expired:'Expirado',pending:'Pendente',sent:'Enviado',confirmed:'Confirmado pelo equipamento',unknown:'Resultado desconhecido',failed:'Falhou',connected:'Conectado',disconnected:'Desconectado',waiting:'Aguardando',claimed:'Em atendimento',closed:'Encerrado',revocation_pending:'Revogação pendente',revoked:'Revogada',company_admin:'Administrador',supervisor:'Supervisor',operator:'Operador',manager:'Síndico / gestor',resident:'Morador'};
const nav=[{label:'PRINCIPAL',items:[['overview','Visão geral',LayoutDashboard],['central','Central de atendimento',Headphones],['companies','Clientes',Building2]]},{label:'GESTÃO DE ACESSOS',items:[['condos','Condomínios',Building2],['people','Pessoas',Users],['invitations','Convites',Ticket],['access-points','Pontos de acesso',DoorOpen],['events','Histórico de acessos',Activity]]},{label:'PLATAFORMA',items:[['brand','White label',Palette],['integrations','Integrações',Link2],['memberships','Equipe e permissões',ShieldCheck]]}];
export default function Dashboard(){
 const[view,setView]=useState<View>('overview'),[config,setConfig]=useState<Row>(),[identity,setIdentity]=useState<Row>(),[companies,setCompanies]=useState<Row[]>([]),[company,setCompany]=useState(''),[rows,setRows]=useState<Row[]>([]),[condos,setCondos]=useState<Row[]>([]),[units,setUnits]=useState<Row[]>([]),[accesses,setAccesses]=useState<Row[]>([]),[devices,setDevices]=useState<Row[]>([]),[people,setPeople]=useState<Row[]>([]),[checks,setChecks]=useState<Row[]>([]),[domains,setDomains]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[search,setSearch]=useState(''),[menu,setMenu]=useState(false),[branding,setBranding]=useState<Row>(),[share,setShare]=useState(''),[loginBusy,setLoginBusy]=useState(false),[panel,setPanel]=useState<Row>(),[supportReason,setSupportReason]=useState(''),[companyFilter,setCompanyFilter]=useState('all');
 const [approvals,setApprovals]=useState<Row[]>([]);
 const kc=useRef<Keycloak|null>(null),mounted=useRef(false);
 const api=useCallback(async(path:string,body?:any,method?:string,overrideCompany?:string)=>{if(!kc.current?.authenticated)throw Error('Entre na sua conta para continuar.');await kc.current.updateToken(40);const r=await fetch(`/api/backend/${path}`,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',Authorization:`Bearer ${kc.current.token}`,...((overrideCompany||company)?{'X-Company-Id':overrideCompany||company}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});let data;try{data=await r.json();}catch{throw Error('Não foi possível ler a resposta do serviço.');}if(!r.ok)throw Error(typeof data.message==='string'?data.message:'Não foi possível concluir a operação.');return data;},[company]);
 useEffect(()=>{if(mounted.current)return;mounted.current=true;fetch('/api/config').then(r=>r.json()).then(async c=>{setConfig(c);if(c.configured){const url=new URL(c.issuer);const realm=url.pathname.split('/realms/')[1];const client=new Keycloak({url:`${url.origin}${url.pathname.split('/realms/')[0]}`,realm,clientId:c.clientId});kc.current=client;try{const ok=await client.init({onLoad:'check-sso',pkceMethod:'S256',checkLoginIframe:false});if(ok){const r=await fetch('/api/backend/me',{headers:{Authorization:`Bearer ${client.token}`}});const me=await r.json();if(!r.ok)throw Error(me.message||'Não foi possível carregar sua conta.');setIdentity(me);}}catch(e){setError(e instanceof Error?e.message:'Não foi possível conectar a autenticação.');}}}).catch(()=>setError('Falha ao carregar configuração.'));fetch(`/api/backend/public/branding?host=${encodeURIComponent(location.hostname)}`).then(r=>r.ok?r.json():null).then(b=>b?.brand&&setBranding(b.brand)).catch(()=>{});if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
 const load=useCallback(async()=>{if(!identity)return;setBusy(true);setError('');try{if(identity.platform){const list=await api('companies');setCompanies(list);}if(company){const [cs,us,as]=await Promise.all([api('condos'),api('records/units'),api('records/access-points')]);setCondos(cs);setUnits(us);setAccesses(as);if(view==='central')setApprovals(await api('access-authorizations'));if(view==='brand'||view==='overview'){const [r,d]=await Promise.all([api('readiness'),api('domains')]);setChecks(r);setDomains(d);}if(['devices','access-points','credentials'].includes(view))setDevices(await api('records/devices'));if(['credentials','vehicles'].includes(view))setPeople(await api('records/people'));const path=view==='central'?'tickets':['condos','invitations','events','memberships','integrations'].includes(view)?view:['overview','companies','brand'].includes(view)?null:`records/${view}`;if(path)setRows(await api(path));else setRows([]);}else setRows([]);}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[identity,api,company,view]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{setRows([]);setCondos([]);setUnits([]);setAccesses([]);setChecks([]);setDomains([]);setPanel(undefined);},[company]);
 useEffect(()=>{if(!identity||!company||!['central','events','integrations'].includes(view))return;const id=setInterval(()=>void load(),10000);return()=>clearInterval(id);},[identity,company,view,load]);
 const current=companies.find(c=>c.id===company);const navigate=(v:View)=>{setView(v);setSearch('');setMenu(false);setError('');setRows([]);};
 const action=async(fn:()=>Promise<any>)=>{setError('');setNotice('');setBusy(true);try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const login=async()=>{if(!config?.configured||!kc.current){setModal('setup');return;}setLoginBusy(true);try{await kc.current.login({acr:{essential:true,values:['2']}});}catch{setError('Não foi possível iniciar a autenticação.');setLoginBusy(false);}};
 const openForm=(kind:string)=>{setNotice('');if(!identity){void login();return;}if(kind!=='companies'&&!company){setError('Selecione uma empresa para continuar.');return;}setModal(kind);};
 const selectCompany=(id:string)=>{if(identity?.platform&&!identity.memberships.some((m:Row)=>m.company_id===id)){setPanel(companies.find(c=>c.id===id));setSupportReason('');setModal('support');}else setCompany(id);};
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));await action(async()=>{let result;const kind=modal;if(kind==='companies'){result=await api('companies',{name:data.name,slug:data.slug});setNotice('Cliente cadastrado. Configure a marca e os acessos para ativar a operação.');}
 else if(kind==='support'){await api(`companies/${panel?.id}/support`,{reason:supportReason});setCompany(panel!.id);setNotice('Sessão de suporte auditada iniciada. Válida por 30 minutos.');}
 else if(kind==='condos')result=await api('condos',{name:data.name,address:data.address});
 else if(kind==='brand'){result=await api(`companies/${company}/brand`,{name:data.name,primary:data.primary,...(data.logo?{logo:data.logo}:{})},'PATCH');}
 else if(kind==='domains')result=await api('domains',{hostname:data.hostname});
 else if(kind==='memberships')result=await api('memberships',{name:data.name,subject:data.subject,role:data.role,condo_ids:data.condo_id?[data.condo_id]:[],unit_ids:data.unit_id?[data.unit_id]:[]});
 else if(kind==='invitations'){result=await api('invitations',{guest_name:data.guest_name,unit_id:data.unit_id,valid_from:new Date(String(data.valid_from)).toISOString(),valid_until:new Date(String(data.valid_until)).toISOString(),access_ids:[data.access_id],...(data.vehicle_plate?{vehicle_plate:String(data.vehicle_plate).toUpperCase()}:{}),request_key:crypto.randomUUID(),channel:'web'});setShare(result.url);}
 else if(kind==='central')result=await api('tickets',{title:data.name,condo_id:data.condo_id,...(data.unit_id?{unit_id:data.unit_id}:{}),...(data.access_id?{access_id:data.access_id}:{})});
 else if(kind==='open')result=await api('commands',{access_id:panel!.id,reason:data.reason,request_key:crypto.randomUUID(),...(data.authorization_id?{authorization_id:data.authorization_id}:{})});
 else if(kind==='agents'){result=await api('agents',{name:data.name,condo_id:data.condo_id});setShare(result.token);}
 else {const payload:Row={name:data.name};for(const [k,v]of Object.entries(data))if(!['condo_id','unit_id','name'].includes(k)&&v!=='')payload[k]=v;if(kind==='access-points')payload.credential_types=String(data.credential_types).split(',');if(kind==='devices'){payload.adapter='http-relay-v1';payload.capabilities=[];}if(kind==='incidents')payload.status='open';if(kind==='credentials')payload.status='pending';result=await api(`records/${kind}`,{condo_id:data.condo_id,...(data.unit_id?{unit_id:data.unit_id}:{}),data:payload});}
 setModal('');if(!['companies','support'].includes(kind))setNotice(kind==='open'?'Solicitação enviada. A confirmação do equipamento será registrada separadamente.':'Salvo com sucesso.');});};
 const selectableCompanies=identity?.platform?companies:identity?.memberships.map((m:Row)=>({id:m.company_id,name:m.company_name||m.name}))||[];
 const companyRows=companies.filter(c=>(companyFilter==='all'||c.status===companyFilter)&&c.name.toLowerCase().includes(search.toLowerCase()));
 const filtered=rows.filter(r=>JSON.stringify([r.name,r.data?.name,r.guest_name,r.title,r.kind]).toLowerCase().includes(search.toLowerCase()));
 const renderEmpty=(kind:View)=>{const names:Partial<Record<View,[string,string]>>={companies:['Seu próximo cliente começa aqui','Cadastre uma empresa e dê a ela uma experiência com a própria marca.'],condos:['Adicione seu primeiro condomínio','Organize unidades, pessoas e acessos em um único lugar.'],invitations:['Nenhum convite por aqui','Os convites criados no app, na web ou pelo WhatsApp aparecerão aqui.'],central:['Sua central está pronta para começar','Os atendimentos aparecerão aqui quando seus condomínios estiverem conectados.'],events:['Cada acesso conta uma história','Autorizações, comandos e passagens serão registrados separadamente.'],integrations:['Conecte sua operação','Configure seus equipamentos e canais de atendimento.']};const [title,desc]=names[kind]||['Tudo pronto para o primeiro cadastro','Os registros reais da sua operação aparecerão aqui.'];return <div className="empty"><div className="empty-illustration"><div className="illustration-orbit"/><div className="illustration-card"><Building2 size={32}/><i/><i/></div><span className="illustration-plus"><Plus size={17}/></span></div><h3>{title}</h3><p>{desc}</p>{!['events','central','integrations'].includes(kind)&&<button className="btn primary" onClick={()=>openForm(kind)}><Plus size={16}/> {kind==='companies'?'Cadastrar primeiro cliente':'Adicionar cadastro'}</button>}{!company&&kind!=='companies'&&<small>Selecione um cliente para acessar a operação.</small>}</div>;};
 return <div className="app-shell" style={branding?.primary?{'--accent':branding.primary} as CSSProperties:undefined}>
 <aside className={`sidebar ${menu?'visible':''}`}><a className="wordmark" href="/"><img src={branding?.logo||'/icon.svg'} width="34" height="34" alt=""/><span>{branding?.name||'vértice'}<small>PORTARIA REMOTA</small></span></a><div className="workspace-switch"><span className="workspace-icon"><ShieldCheck size={19}/></span><div><strong>{identity?.platform?'Minha plataforma':'Área de trabalho'}</strong><small>{identity?'Conta autenticada':'Configuração inicial'}</small></div><ChevronDown size={15}/></div><nav>{nav.map(group=><div className="nav-group" key={group.label}><p>{group.label}</p>{group.items.filter(([id])=>id!=='companies'||!identity||identity.platform).map(([id,label,Icon])=>{const I=Icon as typeof Building2;return <button key={String(id)} className={`nav-item ${view===id?'selected':''}`} onClick={()=>navigate(id as View)}><I size={18}/><span>{String(label)}</span>{id==='central'&&<span className="nav-dot"/>}</button>;})}</div>)}</nav><div className="sidebar-bottom"><div className="security-note"><span><ShieldCheck size={17}/> Feito para proteger</span><p>Controle, cuidado e confiança.<br/>Em cada acesso.</p></div><button className="profile" onClick={()=>identity?kc.current?.logout({redirectUri:location.origin}):login()}><span className="avatar">{identity?'AD':<LogIn size={17}/>}</span><span><strong>{identity?'Minha conta':'Acessar plataforma'}</strong><small>{identity?'Encerrar sessão':'Entrar com segurança'}</small></span>{identity?<LogOut size={16}/>:<ChevronRight size={16}/>}</button></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Abrir menu"><Menu size={20}/></button><span>Plataforma</span><ChevronRight size={13}/><strong>{titles[view]}</strong></div><div className="top-actions"><span className={`connection ${identity?'online':''}`}><i/>{identity?'Sessão protegida':'Ambiente inicial'}</span><span className="top-divider"/><button className="icon-button" title="Guia de configuração" onClick={()=>setModal('setup')}><HelpCircle size={19}/></button><button className="top-avatar" title="Sua conta" onClick={()=>identity?setModal('account'):login()}>{identity?'AD':<LogIn size={16}/>}</button></div></header>
 <main><div className="page-title"><div><div className="eyebrow">{view==='overview'?'SEU CENTRO DE CONTROLE':view==='companies'?'RELACIONAMENTOS QUE CRESCEM':'OPERAÇÃO CONECTADA'}</div><h1>{titles[view]}</h1><p>{view==='overview'?'Uma visão clara de tudo o que você está construindo.':view==='companies'?'Cada cliente, sua marca. Toda a gestão em um só lugar.':'Gerencie sua operação com clareza, do início ao fim.'}</p></div><div className="title-actions">{view==='overview'||view==='companies'?<button className="btn primary" onClick={()=>openForm('companies')}><Plus size={17}/> Novo cliente</button>:<><button className="btn secondary" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/></button>{!['events','brand','integrations'].includes(view)&&<button className="btn primary" onClick={()=>openForm(view)}><Plus size={17}/> Adicionar</button>}</>}</div></div>
 {error&&<div role="alert" className="alert error"><AlertCircle size={18}/><span>{error}</span><button onClick={()=>setError('')} aria-label="Fechar"><X size={16}/></button></div>}{notice&&<div role="status" className="alert success"><CheckCircle2 size={18}/><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="Fechar"><X size={16}/></button></div>}
 {!identity&&<div className="setup-banner"><span className="setup-icon"><LockKeyhole size={19}/></span><div><strong>Um começo seguro, do seu jeito.</strong><p>{config?.configured?'Entre na sua conta para cadastrar seus clientes reais.':'Conecte a infraestrutura e crie sua conta para começar a operação.'}</p></div><button onClick={()=>void login()}>{loginBusy?'Conectando…':config?.configured?'Entrar na conta':'Configurar plataforma'}<ArrowRight size={16}/></button></div>}
 {identity&&<div className="scope-bar"><Building2 size={16}/><span>Cliente em operação</span><select value={company} onChange={e=>e.target.value?selectCompany(e.target.value):setCompany('')}><option value="">Selecione uma empresa</option>{selectableCompanies.map((c:Row)=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{company&&<span className="tag">{current?.status?labels[current.status]:'Acesso autorizado'}</span>}</div>}
 {view==='overview'&&<><div className="stats-grid">{[[Building2,'Clientes cadastrados',identity?companies.length:'—','Sua carteira de clientes'],[CheckCircle2,'Clientes ativos',identity?companies.filter(c=>c.status==='active').length:'—','Operações em funcionamento'],[Globe2,'Domínios conectados',company?domains.filter(d=>d.tls_checked_at).length:'—','Identidades próprias'],[ShieldCheck,'Etapas concluídas',company?`${checks.filter(c=>c.complete).length}/${checks.length}`:'—','Configuração do cliente']].map(([Icon,label,count,caption])=>{const I=Icon as typeof Building2;return <article className="stat-card" key={String(label)}><div><span>{String(label)}</span><I size={18}/></div><strong>{String(count)}</strong><small>{String(caption)}</small></article>;})}</div>
 <section className="welcome-card"><div className="welcome-copy"><span className="light-pill"><span/> SUA PLATAFORMA, SUA MARCA</span><h2>Grandes operações<br/>começam com confiança.</h2><p>Traga seus clientes para uma experiência de portaria<br className="desktop-only"/> mais próxima, organizada e conectada.</p><button onClick={()=>openForm('companies')}>Cadastrar meu primeiro cliente<ArrowUpRight size={17}/></button></div><div className="building-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="building back"><i/><i/><i/><i/><i/><i/></div><div className="building front">{Array.from({length:12},(_,i)=><i key={i}/>)}<span className="building-door"/></div><div className="art-badge"><ShieldCheck size={24}/></div><div className="art-label"><span/> Acesso sob controle</div><div className="ground-line"/></div></section>
 <div className="overview-columns"><section className="card getting-started"><div className="section-heading"><div><h2>Vamos dar os primeiros passos</h2><p>Da primeira empresa à primeira operação.</p></div><span className="muted-pill">{company?checks.filter(c=>c.complete).length:0} de {company?checks.length:4}</span></div><div className="steps">{(company?checks:[{label:'Cadastre seu primeiro cliente',description:'Adicione a empresa que você vai atender.'},{label:'Deixe a marca do seu cliente',description:'Personalize nome, cores e domínio.'},{label:'Conecte o primeiro condomínio',description:'Organize os acessos e os equipamentos.'},{label:'Ative a operação',description:'Revise a configuração e comece com segurança.'}]).map((step:Row,i:number)=><button className="step" key={i} onClick={()=>i===0&&!company?openForm('companies'):navigate(i===1?'brand':i===2?'condos':'integrations')}><span className={`step-number ${step.complete?'done':''}`}>{step.complete?<Check size={15}/>:String(i+1).padStart(2,'0')}</span><span><strong>{step.label}</strong><small>{step.description||(step.complete?'Etapa concluída':'Aguardando configuração')}</small></span><ChevronRight size={17}/></button>)}</div></section><section className="card quick-access"><div className="section-heading"><div><h2>Uma operação. Muitas conexões.</h2><p>Os canais que aproximam sua portaria.</p></div></div>{[[Smartphone,'Aplicativo do morador','Convites e acessos na palma da mão.','invitations'],[MessageCircle,'WhatsApp','Convites antecipados, sem complicação.','integrations'],[Headphones,'Central de atendimento','Câmeras, interfonia e cuidado humano.','central']].map(([Icon,title,desc,v])=>{const I=Icon as typeof Building2;return <button className="quick-row" key={String(title)} onClick={()=>navigate(v as View)}><span className="quick-icon"><I size={20}/></span><span><strong>{String(title)}</strong><small>{String(desc)}</small></span><ArrowUpRight size={15}/></button>;})}<div className="note"><LockKeyhole size={14}/><span>Cada empresa tem seu próprio espaço e permissões.</span></div></section></div>
 <section className="card clients-preview"><div className="section-heading"><div><h2>Seus clientes</h2><p>Relacionamentos que fazem a sua operação crescer.</p></div><button className="text-button" onClick={()=>navigate('companies')}>Ver todos<ArrowRight size={15}/></button></div>{companies.length?<CompanyTable rows={companies.slice(0,5)} onSelect={selectCompany}/>:renderEmpty('companies')}</section></>}
 {view==='companies'&&<section className="card"><div className="table-toolbar"><div className="tabs">{[['all','Todos os clientes'],['active','Ativos'],['draft','Em configuração']].map(([id,label])=><button key={id} onClick={()=>setCompanyFilter(id)} className={companyFilter===id?'active':''}>{label}{id==='all'&&<span>{companies.length}</span>}</button>)}</div><SearchField value={search} set={setSearch}/></div>{companyRows.length?<CompanyTable rows={companyRows} onSelect={selectCompany}/>:renderEmpty('companies')}</section>}
 {view==='brand'&&<div className="brand-layout"><section className="card settings-card"><div className="section-heading"><div><h2>Identidade do cliente</h2><p>A marca aparece no painel e na versão web instalável.</p></div><Palette size={21}/></div><div className="brand-preview" style={{background:current?.brand?.primary||'#147d64'}}><ShieldCheck size={32}/><h2>{current?.brand?.name||'A marca do seu cliente'}</h2><p>PORTARIA REMOTA</p></div><button className="btn secondary" onClick={()=>openForm('brand')}>Personalizar identidade<ArrowUpRight size={16}/></button><p className="form-note">Os aplicativos Android e iPhone usam a marca Vértice.</p></section><section className="card settings-card"><div className="section-heading"><div><h2>Domínio próprio</h2><p>Um endereço que pertence à sua marca.</p></div><Globe2 size={21}/></div>{domains.map(d=><div className="domain-row" key={d.id}><strong>{d.hostname}</strong><span className="tag">{d.auth_configured_at?'Pronto para uso':d.tls_checked_at?'Login pendente':d.verified_at?'HTTPS pendente':'DNS pendente'}</span><p>TXT: <code>_portaria.{d.hostname}</code></p><code className="copy-code">{d.verification_token}</code><p>CNAME: {config?.domainTarget||'Configure o destino da plataforma'}</p><button className="btn secondary" onClick={()=>action(()=>api(`domains/${d.id}/verify`))}>Verificar DNS</button></div>)}{!domains.length&&<div className="small-empty"><Globe2 size={30}/><p>Nenhum domínio conectado.</p></div>}<button className="btn secondary" onClick={()=>openForm('domains')}><Plus size={16}/> Adicionar domínio</button></section>{company&&<section className="card settings-card"><h2>Ativação da operação</h2>{checks.map(c=><p className="check-row" key={c.key}>{c.complete?<CheckCircle2 size={17}/>:<Clock3 size={17}/>} {c.label}</p>)}<button className="btn primary" disabled={busy||checks.some(c=>!c.complete)||!checks.length} onClick={()=>action(()=>api(`companies/${company}/activate`,{}))}>Ativar cliente</button><button className="btn danger" onClick={()=>setModal('suspend')}>Suspender operação</button></section>}</div>}
 {view==='integrations'&&<div className="integrations-grid">{[[MessageCircle,'WhatsApp','whatsapp','Convites antecipados via Whatsmeow. Uma sessão por empresa.'],[Video,'Câmeras ao vivo','media','Vídeo dos acessos para a equipe da central.'],[Headphones,'Interfonia','telephony','Atenda as chamadas do condomínio pelo navegador.'],[Radio,'Agente local','agent','Conexão protegida entre a plataforma e os equipamentos.']].map(([Icon,title,id,desc])=>{const I=Icon as typeof Building2;const status=rows.find(r=>r.kind===id)?.status;return <section className="card integration-card" key={String(id)}><span className="integration-icon"><I size={24}/></span><span className={`tag ${status==='connected'?'green':''}`}>{status?labels[status]||status:'Não configurado'}</span><h2>{String(title)}</h2><p>{String(desc)}</p><button className="btn secondary" onClick={()=>id==='agent'?openForm('agents'):id==='media'?navigate('cameras'):id==='telephony'?navigate('intercoms'):setModal('whatsapp')}>Configurar<ArrowUpRight size={15}/></button></section>;})}<section className="card integration-foot"><ShieldCheck size={21}/><div><h3>Conexões com responsabilidade</h3><p>Recursos ficam disponíveis após configuração e testes com seus equipamentos reais.</p></div><button className="text-button" onClick={()=>navigate('devices')}>Gerenciar equipamentos<ArrowRight size={15}/></button></section></div>}
 {view==='central'&&<div className="central-grid"><section className="card"><div className="section-heading"><h2>Fila de atendimento</h2><span className="muted-pill">{rows.length}</span></div>{rows.length?rows.map(t=><div className="ticket-row" key={t.id}><span className="tag">{labels[t.state]}</span><h3>{t.title}</h3><p>{condos.find(c=>c.id===t.condo_id)?.name}</p>{t.state==='waiting'?<button className="btn primary" onClick={()=>action(()=>api(`tickets/${t.id}/claim`,{}))}>Assumir atendimento</button>:<button className="btn secondary" onClick={()=>action(()=>api(`tickets/${t.id}/close`,{}))}>Encerrar atendimento</button>}</div>):renderEmpty('central')}</section><section className="card settings-card"><TelephonyPanel api={api}/><h2>Acessos disponíveis</h2>{!accesses.length&&<div className="small-empty"><DoorOpen size={32}/><p>Nenhum ponto de acesso conectado.</p></div>}{accesses.map(a=><div className="access-row" key={a.id}><DoorOpen size={22}/><span><strong>{a.data.name}</strong><small>{a.data.mode==='automatic'?'Automático':a.data.mode==='both'?'Credencial e conferência':'Conferência do operador'}</small></span><button className="btn secondary" onClick={()=>{setPanel(a);openForm('open');}}>Liberar</button></div>)}<div className="note"><ShieldCheck size={16}/><span>Uma solicitação de abertura não confirma a passagem de uma pessoa.</span></div><div className="sub-actions"><button className="btn secondary" onClick={()=>navigate('cameras')}><Video size={15}/> Câmeras</button><button className="btn secondary" onClick={()=>navigate('intercoms')}><Headphones size={15}/> Interfonia</button><button className="btn secondary" onClick={()=>navigate('incidents')}>Ocorrências</button></div></section></div>}
 {!['overview','companies','brand','integrations','central'].includes(view)&&<section className="card"><div className="table-toolbar"><div className="tabs"><button className="active">{titles[view]}<span>{rows.length}</span></button></div><SearchField value={search} set={setSearch}/></div>{['condos','people','access-points'].includes(view)&&<div className="subnav">{(view==='condos'?['condos','units']:view==='people'?['people','vehicles','credentials']:['access-points','devices','cameras','intercoms']).map(v=><button key={v} className={v===view?'active':''} onClick={()=>navigate(v as View)}>{titles[v as View]}</button>)}</div>}{view==='cameras'&&filtered.length>0&&<div className="camera-grid">{filtered.map(c=><CameraPlayer key={c.id} camera={c} api={api}/>)}</div>}{busy?<div className="loading"><Loader2 className="spin" size={22}/> Carregando registros…</div>:filtered.length?<div className="table-scroll"><table><thead><tr><th>{view==='events'?'Evento':'Nome / identificação'}</th><th>Contexto</th><th>Situação</th><th/></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.data?.name||r.guest_name||r.name||r.kind}</strong><small>{r.data?.plate||r.data?.type||r.subject||new Date(r.created_at).toLocaleString('pt-BR')}</small></td><td>{condos.find(c=>c.id===r.condo_id)?.name||r.channel||'—'}</td><td><span className="tag">{labels[r.status||r.data?.status||r.role]||r.status||r.data?.mode||(r.data?.homologated?'Homologado':'Cadastrado')}</span></td><td>{view==='invitations'&&r.status==='active'?<button className="text-button" onClick={()=>action(()=>api(`invitations/${r.id}/cancel`,{}))}>Cancelar</button>:view==='credentials'&&!['revoked','revocation_pending'].includes(r.data.status)?<button className="text-button" onClick={()=>action(()=>api(`credentials/${r.id}/revoke`,{}))}>Revogar</button>:<button className="icon-button" aria-label="Ver detalhes" onClick={()=>{setPanel(r);setModal('details');}}><ChevronRight size={17}/></button>}</td></tr>)}</tbody></table></div>:renderEmpty(view)}</section>}
 <footer><span>Vértice <i/> Tecnologia que cuida de cada acesso.</span><span><LockKeyhole size={12}/> Sua operação em um ambiente protegido</span></footer>
 </main></div>
 {modal&&<div className="modal-backdrop" onClick={()=>!busy&&setModal('')}><section className="modal" role="dialog" aria-modal="true" aria-label={modal==='setup'?'Configuração inicial':'Cadastro'} onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" onClick={()=>setModal('')} aria-label="Fechar"><X size={20}/></button>
 {modal==='setup'?<><span className="modal-symbol"><Settings2 size={24}/></span><h2>Prepare sua plataforma</h2><p>O painel está pronto para se conectar aos serviços da sua operação.</p><ol className="setup-list"><li><strong>Inicie a infraestrutura</strong><span>Banco de dados, autenticação e processamento de tarefas.</span></li><li><strong>Crie sua conta de administrador</strong><span>Use seu e-mail real e configure a autenticação em dois fatores.</span></li><li><strong>Cadastre seus clientes</strong><span>Adicione as empresas, personalize suas marcas e conecte os condomínios.</span></li></ol><div className="note"><ShieldCheck size={18}/><span>Nenhum cliente fictício será criado. O guia de instalação está no README do projeto.</span></div><button className="btn primary full" onClick={()=>setModal('')}>Entendi<Check size={16}/></button></>:
 modal==='account'?<><h2>Sua conta</h2><p>{identity?.platform?'Administrador da plataforma':'Usuário autenticado'}</p><button className="btn secondary" onClick={()=>kc.current?.accountManagement()}>Gerenciar conta</button><button className="btn secondary" onClick={()=>action(async()=>{const result=await api('whatsapp/link-code',{});setShare(result.message);setModal('');})}>Vincular WhatsApp</button></>:
 modal==='details'?<><h2>{panel?.data?.name||panel?.guest_name||'Detalhes do registro'}</h2><dl className="details">{Object.entries(panel?.data||panel||{}).filter(([k])=>!['company_id','credential_hash','token_hash'].includes(k)).map(([k,v])=><div key={k}><dt>{({name:'Nome',plate:'Placa',status:'Situação',type:'Tipo',description:'Descrição',severity:'Prioridade',address:'Endereço',mode:'Modo de acesso',reference:'Referência',created_at:'Criado em',kind:'Evento',actor:'Responsável'} as Row)[k]||k.replaceAll('_',' ')}</dt><dd>{typeof v==='object'?JSON.stringify(v):labels[String(v)]||String(v)}</dd></div>)}</dl></>:
 modal==='whatsapp'?<WhatsAppPanel api={api}/>:
modal==='suspend'?<><h2>Suspender {current?.name}?</h2><p>O acesso à plataforma e novas autorizações desta empresa serão interrompidos. Credenciais já gravadas em equipamentos precisam ser tratadas localmente.</p><button className="btn danger" disabled={busy} onClick={()=>action(async()=>{await api(`companies/${company}/suspend`,{});setCompany('');setModal('');})}>Confirmar suspensão</button></>:
 <form onSubmit={save}><span className="modal-symbol">{modal==='support'?<ShieldCheck size={25}/>:<Plus size={25}/>}</span><h2>{modal==='support'?`Acessar ${panel?.name}`:modal==='open'?`Liberar ${panel?.data?.name}`:modal==='brand'?'Personalizar identidade':modal==='domains'?'Conectar domínio':modal==='agents'?'Cadastrar agente local':modal==='companies'?'Novo cliente':`Adicionar ${titles[modal as View]?.toLowerCase()||'cadastro'}`}</h2><p>{modal==='support'?'Informe o motivo. Este acesso será registrado e expirará em 30 minutos.':modal==='companies'?'Comece pelos dados da empresa. A identidade visual vem no próximo passo.':'Preencha os dados reais da sua operação.'}</p>
 {modal==='support'?<Field label="Motivo do acesso" name="reason" minLength={10} value={supportReason} onChange={(e:any)=>setSupportReason(e.target.value)} placeholder="Descreva a configuração ou atendimento necessário"/>:modal==='open'?<><Field label="Motivo da liberação" name="reason" minLength={5}/>{panel?.data?.mode==='both'&&<Select label="Credencial validada" name="authorization_id" options={approvals.filter(a=>a.access_id===panel.id).map(a=>[a.id,a.guest_name])}/>}</>:modal==='domains'?<Field label="Domínio" name="hostname" placeholder="portaria.suaempresa.com.br"/>:<>
 {modal==='invitations'?<><Field label="Nome do convidado" name="guest_name"/><Select label="Unidade" name="unit_id" options={units.map(u=>[u.id,`${condos.find(c=>c.id===u.condo_id)?.name||''} · ${u.data.name}`])}/><div className="form-grid"><Field label="Início da visita" name="valid_from" type="datetime-local"/><Field label="Fim da visita" name="valid_until" type="datetime-local"/></div><Select label="Acesso permitido" name="access_id" options={accesses.map(a=>[a.id,a.data.name])}/><Field label="Placa do veículo (opcional)" name="vehicle_plate" required={false}/></>:<><Field label={modal==='companies'?'Nome da empresa':modal==='brand'?'Nome exibido na plataforma':'Nome'} name="name" defaultValue={modal==='brand'?current?.brand?.name||current?.name:''}/>{modal==='companies'&&<Field label="Identificador da empresa" name="slug" placeholder="nome-da-empresa" pattern="[a-z0-9]+(-[a-z0-9]+)*"/>}{modal==='brand'?<><Field label="Cor principal" name="primary" type="color" defaultValue={current?.brand?.primary||'#147d64'}/><Field label="Endereço HTTPS do logotipo (opcional)" name="logo" type="url" defaultValue={current?.brand?.logo||''} required={false}/></>:modal==='condos'?<Field label="Endereço" name="address" required={false}/>:!['companies'].includes(modal)&&<Select label="Condomínio" name="condo_id" options={condos.map(c=>[c.id,c.name])} required={modal!=='memberships'}/>}
 {['people','vehicles','credentials','memberships','central'].includes(modal)&&<Select label="Unidade" name="unit_id" options={units.map(u=>[u.id,u.data.name])} required={!['memberships','central'].includes(modal)}/>}
 {modal==='people'&&<Select label="Tipo de pessoa" name="type" options={[["resident","Morador"],["visitor","Visitante"],["provider","Prestador"]]}/>}
 {modal==='memberships'&&<><Field label="Identificador do usuário na autenticação" name="subject"/><Select label="Perfil" name="role" options={Object.entries(labels).filter(([k])=>['company_admin','supervisor','operator','manager','resident'].includes(k))}/><p className="form-note">Crie o usuário real no serviço de autenticação e vincule seu identificador. Moradores precisam de condomínio e unidade.</p></>}
 {modal==='devices'&&<><Field label="Endereço local do dispositivo" name="address" placeholder="Identificador no agente local"/><p className="form-note">O equipamento será cadastrado como não homologado. Sua habilitação depende de testes técnicos.</p></>}
 {['access-points','credentials'].includes(modal)&&<Select label="Equipamento" name="device_id" options={devices.map(d=>[d.id,d.data.name])}/>}
 {modal==='access-points'&&<><Select label="Modo de liberação" name="mode" options={[["automatic","Automático"],["operator","Conferência do operador"],["both","Credencial e conferência"]]}/><Select label="Credenciais temporárias" name="credential_types" options={[["qr,pin","QR Code e senha"],["qr,pin,tag,card,face,plate","Todas as modalidades homologadas"],["qr","QR Code"],["pin","Senha"],["tag,card","Tag e cartão"],["face","Reconhecimento facial"],["plate","Placa de veículo"]]}/></>}
 {['credentials','vehicles'].includes(modal)&&<Select label="Pessoa vinculada" name="person_id" options={people.map(p=>[p.id,p.data.name])}/>}
 {modal==='credentials'&&<><Select label="Tipo de credencial" name="type" options={[["tag","Tag"],["card","Cartão"],["face","Facial"],["plate","Placa"]]}/><Field label="Referência no equipamento" name="reference"/><p className="form-note">A credencial ficará pendente até o equipamento confirmar o provisionamento.</p></>}
 {modal==='vehicles'&&<Field label="Placa" name="plate"/>}
 {['cameras','intercoms','central'].includes(modal)&&<Select label="Ponto de acesso" name="access_id" options={accesses.map(a=>[a.id,a.data.name])} required={modal!=='central'}/>}
 {modal==='cameras'&&<Field label="Caminho da transmissão no servidor de mídia" name="stream_path"/>}
 {modal==='intercoms'&&<Field label="Ramal SIP" name="extension"/>}
 {modal==='incidents'&&<><Field label="Descrição" name="description"/><Select label="Prioridade" name="severity" options={[["info","Informativa"],["warning","Atenção"],["critical","Crítica"]]}/></>}
 </>}
 </>}{error&&<p className="field-error">{error}</p>}<div className="modal-actions"><button className="btn secondary" type="button" onClick={()=>setModal('')}>Cancelar</button><button className="btn primary" disabled={busy} type="submit">{busy?<Loader2 className="spin" size={16}/>:<Check size={16}/>} {modal==='support'?'Iniciar suporte':modal==='open'?'Solicitar abertura':'Salvar'}</button></div></form>}
 </section></div>}
 {share&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Compartilhar"><button className="modal-close icon-button" onClick={()=>setShare('')} aria-label="Fechar"><X size={20}/></button><h2>{share.startsWith('http')?'Convite criado':'Guarde esta informação'}</h2><p>{share.startsWith('http')?'Compartilhe o link com o convidado. Ele não precisa instalar o app.':'Esta informação só será exibida agora. Guarde em um local seguro.'}</p>{share.startsWith('http')&&<div className="qr-box"><QRCodeSVG value={share} size={160}/></div>}<code className="copy-code">{share}</code><button className="btn primary full" onClick={async()=>{try{await navigator.clipboard.writeText(share);setNotice('Copiado.');}catch{setNotice('Selecione o texto para copiar.');}}}><Copy size={16}/> Copiar</button></section></div>}
 </div>;
}
function CompanyTable({rows,onSelect}:{rows:Row[],onSelect:(id:string)=>void}){return <div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Identidade</th><th>Situação</th><th/></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><div className="company-cell"><span style={{background:c.brand?.primary||'#147d64'}}>{c.name.slice(0,2).toUpperCase()}</span><div><strong>{c.name}</strong><small>{c.slug}</small></div></div></td><td>{c.brand?.name||'A configurar'}</td><td><span className={`tag ${c.status==='active'?'green':''}`}>{labels[c.status]}</span></td><td><button className="text-button" onClick={()=>onSelect(c.id)}>Gerenciar<ArrowUpRight size={15}/></button></td></tr>)}</tbody></table></div>;}
function SearchField({value,set}:{value:string,set:(s:string)=>void}){return <label className="search"><Search size={16}/><input aria-label="Buscar registros" placeholder="Buscar..." value={value} onChange={e=>set(e.target.value)}/><kbd>⌕</kbd></label>;}
function Field({label,name,required=true,...rest}:{label:string,name:string,required?:boolean,[key:string]:any}){return <label className="field"><span>{label}</span><input name={name} required={required} maxLength={500} {...rest}/></label>;}
function Select({label,name,options,required=true}:{label:string,name:string,options:string[][],required?:boolean}){return <label className="field"><span>{label}</span><select name={name} required={required} defaultValue=""><option value="">Selecione</option>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;}
