'use client';
import { useEffect,useRef,useState } from 'react';
import { UserAgent,Registerer,SessionState,type Invitation } from 'sip.js';
import { Video,Phone,PhoneOff,RefreshCw,Mic } from 'lucide-react';
type API=(path:string,body?:any,method?:string)=>Promise<any>;
export function CameraPlayer({camera,api}:{camera:any,api:API}){
 const video=useRef<HTMLVideoElement>(null),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{if(!playing)return;const abort=new AbortController();const pc=new RTCPeerConnection();let remote:string|undefined;let sessionToken='';let renewal:ReturnType<typeof setTimeout>;let closed=false;
  async function start(){try{const session=await api(`cameras/${camera.id}/session`,{});if(closed)return;sessionToken=session.token;pc.addTransceiver('video',{direction:'recvonly'});pc.addTransceiver('audio',{direction:'recvonly'});pc.ontrack=e=>{if(video.current)video.current.srcObject=e.streams[0]||new MediaStream([e.track]);};await pc.setLocalDescription(await pc.createOffer());if(pc.iceGatheringState!=='complete')await new Promise<void>(resolve=>{const timer=setTimeout(resolve,2500);pc.addEventListener('icegatheringstatechange',()=>{if(pc.iceGatheringState==='complete'){clearTimeout(timer);resolve();}});});if(closed)return;const r=await fetch(session.url,{method:'POST',headers:{Authorization:`Bearer ${session.token}`,'Content-Type':'application/sdp'},body:pc.localDescription?.sdp,signal:abort.signal});if(!r.ok)throw Error('A câmera não está disponível ou a sessão não foi autorizada.');const loc=r.headers.get('location');if(loc)remote=new URL(loc,session.url).toString();await pc.setRemoteDescription({type:'answer',sdp:await r.text()});setError('');renewal=setTimeout(()=>setAttempt(v=>v+1),50000);}catch(e){if(!closed)setError((e as Error).message);}}
  void start();return()=>{closed=true;abort.abort();clearTimeout(renewal);pc.close();if(remote)void fetch(remote,{method:'DELETE',headers:{Authorization:`Bearer ${sessionToken}`}}).catch(()=>{});if(video.current)video.current.srcObject=null;};
 },[playing,attempt,camera.id,api]);
 return <div className="camera-player"><div className="camera-surface">{playing?<video ref={video} autoPlay playsInline muted controls/>:<><Video size={28}/><span>Transmissão sob demanda</span></>}{error&&<div className="camera-error">{error}</div>}</div><div className="camera-toolbar"><strong>{camera.data.name}</strong><button className="btn secondary" onClick={()=>{setError('');setPlaying(!playing);}}>{playing?'Parar vídeo':'Ver ao vivo'}</button>{playing&&<button className="icon-button" aria-label="Reconectar câmera" onClick={()=>setAttempt(v=>v+1)}><RefreshCw size={16}/></button>}</div></div>;
}
export function TelephonyPanel({api}:{api:API}){
 const[status,setStatus]=useState('Desconectado'),[error,setError]=useState(''),[ringing,setRinging]=useState(false),[inCall,setInCall]=useState(false);const ua=useRef<UserAgent|null>(null),registration=useRef<Registerer|null>(null),call=useRef<Invitation|null>(null),audio=useRef<HTMLAudioElement>(null);
 useEffect(()=>()=>{void registration.current?.unregister().catch(()=>{});void ua.current?.stop();ua.current=null;},[api]);
 async function connect(){try{setError('');setStatus('Conectando');const c=await api('telephony/account');const uri=UserAgent.makeURI(`sip:${c.username}@${c.domain}`);if(!uri)throw Error('Configuração de interfonia inválida.');const agent=new UserAgent({uri,transportOptions:{server:c.server},authorizationUsername:c.username,authorizationPassword:c.password,logLevel:'error',sessionDescriptionHandlerFactoryOptions:{constraints:{audio:true,video:false}},delegate:{onInvite(invitation){if(call.current){void invitation.reject({statusCode:486});return;}call.current=invitation;setRinging(true);invitation.stateChange.addListener(state=>{if(state===SessionState.Established){setRinging(false);setInCall(true);setStatus('Em chamada');const handler=invitation.sessionDescriptionHandler as any;const connection:RTCPeerConnection|undefined=handler?.peerConnection;if(connection&&audio.current){const stream=new MediaStream();connection.getReceivers().forEach(r=>r.track&&stream.addTrack(r.track));audio.current.srcObject=stream;void audio.current.play().catch(()=>setError('Toque no controle de áudio para ouvir a chamada.'));}}if(state===SessionState.Terminated){call.current=null;setRinging(false);setInCall(false);setStatus('Disponível');}});}}});ua.current=agent;await agent.start();registration.current=new Registerer(agent);await registration.current.register({requestDelegate:{onAccept:()=>setStatus('Disponível'),onReject:()=>{setStatus('Falha no registro');setError('A central de telefonia recusou sua conta.');}}});}catch(e){setError((e as Error).message);setStatus('Desconectado');}}
 async function answer(){try{await call.current?.accept({sessionDescriptionHandlerOptions:{constraints:{audio:true,video:false}}});}catch(e){setError('Não foi possível atender. Verifique a permissão do microfone.');}}
 async function hangup(){if(!call.current)return;try{if(call.current.state===SessionState.Established)await call.current.bye();else await call.current.reject();}catch{setError('Não foi possível encerrar a chamada.');}}
 return <div className="telephony-panel"><div className="access-row"><Phone size={21}/><span><strong>Interfonia da central</strong><small>{status}</small></span>{!ua.current&&<button className="btn secondary" onClick={()=>void connect()}>Conectar</button>}</div>{ringing&&<div className="call-actions"><span>Chamada recebida</span><button className="btn primary" onClick={()=>void answer()}><Mic size={15}/> Atender</button><button className="btn danger" onClick={()=>void hangup()}><PhoneOff size={15}/> Recusar</button></div>}{inCall&&<button className="btn danger" onClick={()=>void hangup()}><PhoneOff size={15}/> Encerrar chamada</button>}{error&&<p className="field-error">{error}</p>}<audio ref={audio} autoPlay controls={inCall}/></div>;
}
