[modules]
autoload=yes
noload => chan_alsa.so
noload => chan_console.so
noload => chan_dahdi.so
noload => chan_motif.so
noload => chan_sip.so
noload => res_pjsip_transport_tcp.so
noload => res_pjsip_transport_udp.so
load => res_pjsip_transport_websocket.so
load => res_http_websocket.so
load => app_queue.so
load => app_userevent.so
load => res_manager_devicestate.so
