[general]
persistentmembers = no
autofill = yes
monitor-type = MixMonitor
shared_lastcall = yes

[portaria-unprovisioned]
strategy = ringall
timeout = 20
retry = 0
maxlen = 0
joinempty = no
leavewhenempty = yes
