import { Controller,Get,Post,Patch,Body,Param,Req,Res,Sse,ForbiddenException,UnauthorizedException,NotFoundException,BadRequestException,ConflictException } from '@nestjs/common';
import { ApiBearerAuth,ApiTags,ApiOperation } from '@nestjs/swagger';
import type { Request,Response } from 'express';
import { interval,mergeMap,startWith } from 'rxjs';
import { z } from 'zod';
import { resolveTxt,resolveCname } from 'node:dns/promises';
import { timingSafeEqual } from 'node:crypto';
import { db,auth,core,env,whatsapp } from './runtime';
import { one,type Scope,type Sql } from './db';
import { hash,token,requireRole } from './security';
import { admins,operators } from './core';
import { uuid,companySchema,brandSchema,membershipSchema,recordSchemas } from './schemas';
export function secret(actual:string|undefined,expected:string|undefined){if(!actual||!expected||Buffer.byteLength(actual)!==Buffer.byteLength(expected)||!timingSafeEqual(Buffer.from(actual),Buffer.from(expected)))throw new UnauthorizedException();}
export async function tenant<T>(req:Request,fn:(q:Sql,s:Scope)=>Promise<T>){const identity=await auth.identity(req.headers.authorization);const company=uuid.parse(req.headers['x-company-id']);const s=await auth.scope(identity,company);return db.transaction(s,async q=>{const c=await one(q,'SELECT status FROM companies WHERE id=$1',[company]);if(!c||c.status==='suspended')throw new ForbiddenException('Empresa indisponível.');return fn(q,s);});}
async function platform<T>(req:Request,fn:(q:Sql,s:Scope)=>Promise<T>){const id=await auth.identity(req.headers.authorization);if(!id.platform)throw new ForbiddenException();const s:Scope={subject:id.subject,platform:true};return db.transaction(s,q=>fn(q,s));}
export async function agent<T>(req:Request,fn:(q:Sql,s:Scope)=>Promise<T>){const value=req.headers.authorization?.replace(/^Bearer /,'');if(!value)throw new UnauthorizedException();return db.transaction({subject:'agent'},async q=>{const a=await one(q,'SELECT * FROM app.resolve_agent($1)',[hash(value)]);if(!a)throw new UnauthorizedException();const s:Scope={subject:`agent:${a.id}`,company:a.company_id,role:'agent',condos:[a.condo_id]};await q.query("SELECT set_config('app.company',$1,true),set_config('app.role','agent',true),set_config('app.condos',$2,true),set_config('app.subject',$3,true)",[s.company,a.condo_id,s.subject]);await q.query('UPDATE agent_keys SET last_seen=now() WHERE id=$1',[a.id]);return fn(q,s);});}
@ApiTags('Plataforma') @ApiBearerAuth() @Controller('v1')
export class ApiController {
 @Get('health') async health(){await db.pool.query('SELECT 1');return{status:'ok'};}
 @Get('me') me(@Req() req:Request){return auth.identity(req.headers.authorization);}
 @Get('companies') companies(@Req() req:Request){return platform(req,q=>q.query('SELECT * FROM companies ORDER BY created_at DESC').then(r=>r.rows));}
 @Post('companies') @ApiOperation({summary:'Cadastrar empresa real, sem dados de demonstração'}) createCompany(@Req() req:Request,@Body() body:any){const b=companySchema.parse(body);return platform(req,q=>one(q,'INSERT INTO companies(name,slug) VALUES($1,$2) RETURNING *',[b.name,b.slug]));}
 @Patch('companies/:id/brand') brand(@Req() req:Request,@Param('id') id:string,@Body() body:any){const b=brandSchema.parse(body);return platform(req,q=>one(q,'UPDATE companies SET brand=$1 WHERE id=$2 RETURNING *',[b,uuid.parse(id)]));}
 @Post('companies/:id/support') support(@Req() req:Request,@Param('id') id:string,@Body() body:any){const reason=z.string().trim().min(10).max(500).parse(body.reason);return platform(req,async(q,s)=>{const row=await one(q,"INSERT INTO support_grants(company_id,subject,reason,expires_at) VALUES($1,$2,$3,now()+interval '30 minutes') RETURNING *",[uuid.parse(id),s.subject,reason]);await q.query("SELECT set_config('app.company',$1,true),set_config('app.role','support',true)",[id]);await core.event(q,{...s,company:id,role:'support'},'support.started',row.id,undefined,{reason,expires_at:row.expires_at});return row;});}
 @Post('companies/:id/suspend') suspend(@Req() req:Request,@Param('id') id:string){return platform(req,q=>one(q,"UPDATE companies SET status='suspended' WHERE id=$1 RETURNING *",[uuid.parse(id)]));}
 @Post('companies/:id/activate') activate(@Req() req:Request,@Param('id') id:string){return platform(req,async(q,s)=>{uuid.parse(id);await q.query("SELECT set_config('app.company',$1,true),set_config('app.role','support',true)",[id]);const checks=await readiness(q,id);if(checks.some(c=>!c.complete))throw new ConflictException({message:'Há etapas de configuração pendentes.',checks});const row=await one(q,"UPDATE companies SET status='active' WHERE id=$1 RETURNING *",[id]);await core.event(q,{...s,company:id,role:'support'},'company.activated',id);return row;});}
 @Get('readiness') ready(@Req() req:Request){return tenant(req,async(q,s)=>{requireRole(s,admins);return readiness(q,s.company!);});}
 @Get('domains') domains(@Req() req:Request){return tenant(req,async(q,s)=>{requireRole(s,admins);return(await q.query('SELECT * FROM domains ORDER BY created_at')).rows;});}
 @Post('domains') domain(@Req() req:Request,@Body() body:any){const host=z.string().toLowerCase().regex(/^(?=.{4,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/).parse(body.hostname);return tenant(req,async(q,s)=>{requireRole(s,admins);return one(q,'INSERT INTO domains(company_id,hostname,verification_token) VALUES($1,$2,$3) RETURNING *',[s.company,host,token()]);});}
 @Post('domains/:id/verify') verifyDomain(@Req() req:Request,@Param('id') id:string){return tenant(req,async(q,s)=>{requireRole(s,admins);const d=await one(q,'SELECT * FROM domains WHERE id=$1',[uuid.parse(id)]);if(!d)throw new NotFoundException();let txt:string[][]=[],cnames:string[]=[];try{[txt,cnames]=await Promise.all([resolveTxt(`_portaria.${d.hostname}`),resolveCname(d.hostname)]);}catch{throw new BadRequestException('Registros DNS ainda não encontrados.');}if(!env.DOMAIN_TARGET||!txt.some(parts=>parts.join('')===d.verification_token)||!cnames.map(c=>c.replace(/\.$/,'')).includes(env.DOMAIN_TARGET))throw new BadRequestException('O TXT de verificação e o CNAME precisam corresponder às instruções.');await q.query('UPDATE domains SET verified_at=now() WHERE id=$1',[id]);await core.event(q,s,'domain.verified',id);return{verified:true,tls:'pending'};});}
 @Get('public/branding') async branding(@Req() req:Request){const host=z.string().max(253).parse(req.query.host);return db.transaction({subject:'public'},q=>one(q,'SELECT * FROM app.resolve_host($1)',[host]));}
 @Get('internal/domain-allowed') domainAllowed(@Req() req:Request){secret((req.headers['x-service-key']||req.query.key) as string,env.INTERNAL_KEY);return db.transaction({subject:'proxy',platform:true},async q=>{const d=await one(q,"SELECT d.id FROM domains d JOIN companies c ON c.id=d.company_id WHERE d.hostname=$1 AND d.verified_at IS NOT NULL AND c.status<>'suspended'",[String(req.query.domain)]);if(!d)throw new ForbiddenException();return{allowed:true};});}
 @Get('condos') condos(@Req() req:Request){return tenant(req,q=>q.query('SELECT * FROM condos ORDER BY name').then(r=>r.rows));}
 @Post('condos') condo(@Req() req:Request,@Body() body:any){const b=z.object({name:z.string().trim().min(1).max(200),address:z.string().max(500).default('')}).strict().parse(body);return tenant(req,async(q,s)=>{requireRole(s,admins);const r=await one(q,'INSERT INTO condos(company_id,name,address) VALUES($1,$2,$3) RETURNING *',[s.company,b.name,b.address]);await core.event(q,s,'condo.created',r.id,r.id);return r;});}
 @Get('memberships') members(@Req() req:Request){return tenant(req,async(q,s)=>{requireRole(s,admins);return(await q.query('SELECT id,subject,name,role,condo_ids,unit_ids,active,whatsapp_verified FROM memberships ORDER BY name')).rows;});}
 @Post('memberships') member(@Req() req:Request,@Body() body:any){const b=membershipSchema.parse(body);return tenant(req,async(q,s)=>{requireRole(s,admins);for(const id of b.condo_ids)if(!await one(q,'SELECT id FROM condos WHERE id=$1',[id]))throw new BadRequestException('Condomínio não pertence à empresa.');for(const id of b.unit_ids){const u=await core.record(q,id,'units');if(!b.condo_ids.includes(u.condo_id))throw new BadRequestException('Unidade fora dos condomínios atribuídos.');}if(b.role==='resident'&&!b.unit_ids.length)throw new BadRequestException('Morador precisa de unidade.');const r=await one(q,'INSERT INTO memberships(company_id,subject,name,role,condo_ids,unit_ids) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[s.company,b.subject,b.name,b.role,b.condo_ids,b.unit_ids]);await core.event(q,s,'member.created',r.id);return r;});}
 @Patch('memberships/:id') updateMember(@Req() req:Request,@Param('id') id:string,@Body() body:any){const active=z.boolean().parse(body.active);return tenant(req,async(q,s)=>{requireRole(s,admins);const m=await one(q,'UPDATE memberships SET active=$1 WHERE id=$2 AND subject<>$3 RETURNING id',[active,uuid.parse(id),s.subject]);if(!m)throw new ConflictException('Não é possível alterar o próprio acesso por esta ação.');await core.event(q,s,active?'member.enabled':'member.disabled',id);return m;});}
 @Get('records/:kind') records(@Req() req:Request,@Param('kind') kind:string){if(!recordSchemas[kind])throw new NotFoundException();return tenant(req,q=>q.query('SELECT * FROM records WHERE kind=$1 ORDER BY created_at DESC LIMIT 500',[kind]).then(r=>r.rows));}
 @Post('records/:kind') record(@Req() req:Request,@Param('kind') kind:string,@Body() body:any){const b=z.object({condo_id:uuid,unit_id:uuid.optional(),data:z.record(z.string(),z.unknown())}).strict().parse(body);return tenant(req,(q,s)=>core.createRecord(q,s,kind,b));}
 @Post('credentials/:id/revoke') revoke(@Req() req:Request,@Param('id') id:string){return tenant(req,async(q,s)=>{requireRole(s,[...admins,'manager']);const r=await core.record(q,uuid.parse(id),'credentials');await q.query("UPDATE records SET data=jsonb_set(data,'{status}','\"revocation_pending\"'),updated_at=now() WHERE id=$1",[id]);await core.event(q,s,'credential.revocation_requested',id,r.condo_id,{},r.unit_id);return{status:'revocation_pending'};});}
 @Get('invitations') invites(@Req() req:Request){return tenant(req,q=>q.query("SELECT id,condo_id,unit_id,guest_name,vehicle_plate,valid_from,valid_until,CASE WHEN status='active' AND valid_until<now() THEN 'expired' ELSE status END AS status,channel,created_at FROM invitations ORDER BY created_at DESC LIMIT 500").then(r=>r.rows));}
 @Post('invitations') invite(@Req() req:Request,@Body() body:any){return tenant(req,(q,s)=>core.invite(q,s,body));}
 @Post('invitations/:id/cancel') cancel(@Req() req:Request,@Param('id') id:string){return tenant(req,(q,s)=>core.cancelInvite(q,s,uuid.parse(id)));}
 @Get('public/invitations/:token') async publicInvite(@Param('token') value:string,@Res({passthrough:true}) res:Response){res.setHeader('Cache-Control','no-store');if(!/^[A-Za-z0-9_-]{43}$/.test(value))throw new NotFoundException();return db.transaction({subject:'guest'},async q=>{const i=await one(q,'SELECT * FROM app.resolve_invite($1)',[hash(value)]);if(!i)throw new NotFoundException();await q.query("SELECT set_config('app.company',$1,true),set_config('app.condos',$2,true),set_config('app.role','guest',true)",[i.company_id,i.condo_id]);return core.publicInvite(q,{subject:'guest',company:i.company_id,condos:[i.condo_id],role:'guest'},i.id);});}
 @Post('commands') open(@Req() req:Request,@Body() body:any){return tenant(req,(q,s)=>core.open(q,s,body));}
 @Get('commands') commands(@Req() req:Request){return tenant(req,async(q,s)=>{requireRole(s,operators);return(await q.query("SELECT *,CASE WHEN state='sent' AND expires_at<now() THEN 'unknown' WHEN state='pending' AND expires_at<now() THEN 'expired' ELSE state END AS state FROM commands ORDER BY created_at DESC LIMIT 100")).rows;});}
 @Get('access-authorizations') authorizations(@Req()req:Request){return tenant(req,async(q,s)=>{requireRole(s,operators);return(await q.query('SELECT a.id,a.access_id,a.expires_at,i.guest_name FROM access_authorizations a JOIN invitations i ON i.id=a.invitation_id WHERE NOT a.used AND a.expires_at>now() ORDER BY a.expires_at')).rows;});}
 @Get('events') events(@Req() req:Request){return tenant(req,q=>q.query('SELECT * FROM events ORDER BY created_at DESC LIMIT 100').then(r=>r.rows));}
 @Sse('events/stream') stream(@Req() req:Request){return interval(5000).pipe(startWith(0),mergeMap(()=>tenant(req,async q=>({data:(await q.query('SELECT * FROM events ORDER BY created_at DESC LIMIT 30')).rows}))));}
 @Get('tickets') tickets(@Req() req:Request){return tenant(req,async(q,s)=>{requireRole(s,operators);return(await q.query("SELECT * FROM tickets WHERE state<>'closed' ORDER BY created_at")).rows;});}
 @Post('tickets') ticket(@Req() req:Request,@Body() body:any){const b=z.object({condo_id:uuid,unit_id:uuid.optional(),access_id:uuid.optional(),title:z.string().trim().min(3).max(200)}).parse(body);return tenant(req,async(q,s)=>{requireRole(s,operators);for(const [key,kind] of [['unit_id','units'],['access_id','access-points']])if((b as any)[key]){const r=await core.record(q,(b as any)[key],kind);if(r.condo_id!==b.condo_id)throw new BadRequestException('Referência de outro condomínio.');}return one(q,'INSERT INTO tickets(company_id,condo_id,unit_id,access_id,title) VALUES($1,$2,$3,$4,$5) RETURNING *',[s.company,b.condo_id,b.unit_id||null,b.access_id||null,b.title]);});}
 @Post('tickets/:id/claim') claim(@Req() req:Request,@Param('id') id:string){return tenant(req,(q,s)=>core.claim(q,s,uuid.parse(id)));}
 @Post('tickets/:id/close') close(@Req() req:Request,@Param('id') id:string){return tenant(req,(q,s)=>core.close(q,s,uuid.parse(id)));}
 @Get('integrations') integrations(@Req() req:Request){return tenant(req,async(q,s)=>{requireRole(s,[...admins,'supervisor']);return(await q.query('SELECT * FROM integrations')).rows;});}
 @Get('agents') agents(@Req() req:Request){return tenant(req,async(q,s)=>{requireRole(s,admins);return(await q.query('SELECT id,name,condo_id,active,last_seen FROM agent_keys')).rows;});}
 @Post('agents') createAgent(@Req() req:Request,@Body() body:any){const b=z.object({name:z.string().min(1).max(200),condo_id:uuid}).parse(body);return tenant(req,async(q,s)=>{requireRole(s,admins);const value=token();const a=await one(q,'INSERT INTO agent_keys(company_id,condo_id,name,token_hash) VALUES($1,$2,$3,$4) RETURNING id,name,condo_id',[s.company,b.condo_id,b.name,hash(value)]);await core.event(q,s,'agent.created',a.id,b.condo_id);return{...a,token:value};});}
 @Post('agents/:id/revoke') revokeAgent(@Req() req:Request,@Param('id') id:string){return tenant(req,async(q,s)=>{requireRole(s,admins);return one(q,'UPDATE agent_keys SET active=false WHERE id=$1 RETURNING id',[uuid.parse(id)]);});}
 @Post('agent/poll') poll(@Req() req:Request){return agent(req,(q,s)=>core.dispatch(q,s));}
 @Post('agent/commands/:id/ack') ack(@Req() req:Request,@Param('id') id:string,@Body() body:any){return agent(req,(q,s)=>core.ack(q,s,uuid.parse(id),z.enum(['confirmed','failed','unknown']).parse(body.state)));}
 @Post('agent/redeem') redeem(@Req() req:Request,@Body() body:any){const b=z.object({credential:z.string().min(8).max(100),access_id:uuid,request_key:z.string().min(16).max(100)}).parse(body);return agent(req,(q,s)=>core.redeem(q,s,b.credential,b.access_id,b.request_key));}
 @Post('agent/events') hardwareEvent(@Req() req:Request,@Body() body:any){const b=z.object({access_id:uuid,kind:z.enum(['passage.detected','door.open','door.closed','device.offline']),source_key:z.string().min(10).max(200)}).parse(body);return agent(req,async(q,s)=>{const a=await core.record(q,b.access_id,'access-points');await q.query('INSERT INTO events(company_id,condo_id,kind,actor,resource_id,source_key) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(company_id,source_key) DO NOTHING',[s.company,a.condo_id,b.kind,s.subject,a.id,b.source_key]);return{received:true};});}
 @Post('whatsapp/link-code') linkCode(@Req() req:Request){return tenant(req,async(q,s)=>{requireRole(s,['resident']);const value=token().slice(0,16);await q.query("INSERT INTO phone_links(company_id,subject,code_hash,expires_at) VALUES($1,$2,$3,now()+interval '10 minutes')",[s.company,s.subject,hash(value)]);return{message:`VINCULAR ${value}`,expires_in:600};});}
 @Post('internal/whatsapp/message') whatsappMessage(@Req() req:Request,@Body() body:any){secret(req.headers['x-service-key'] as string,env.WHATSAPP_KEY);const b=z.object({company_id:uuid,message_id:z.string().min(1).max(200),sender:z.string().regex(/^\+[1-9]\d{7,14}$/),text:z.string().max(2000)}).parse(body);const s:Scope={subject:'whatsmeow',company:b.company_id,role:'support'};return db.transaction(s,async q=>{await core.active(q,s);return{reply:await whatsapp.receive(q,s,b.message_id,b.sender,b.text)};});}
 @Post('internal/whatsapp/status') whatsappStatus(@Req() req:Request,@Body() body:any){secret(req.headers['x-service-key'] as string,env.WHATSAPP_KEY);const b=z.object({company_id:uuid,status:z.enum(['connected','disconnected','logged_out'])}).parse(body);return db.transaction({subject:'whatsmeow',company:b.company_id,role:'support'},q=>q.query("INSERT INTO integrations(company_id,kind,status) VALUES($1,'whatsapp',$2) ON CONFLICT(company_id,kind) DO UPDATE SET status=$2,updated_at=now()",[b.company_id,b.status]).then(()=>({received:true})));}
}
async function readiness(q:Sql,company:string){const count=async(sql:string)=>Number((await one(q,sql,[company]))?.n||0)>0;return[
 {key:'brand',label:'Identidade visual',complete:await count("SELECT count(*) n FROM companies WHERE id=$1 AND length(brand->>'name')>0")},
 {key:'domain',label:'Domínio, HTTPS e login autorizados',complete:await count('SELECT count(*) n FROM domains WHERE company_id=$1 AND verified_at IS NOT NULL AND tls_checked_at IS NOT NULL AND auth_configured_at IS NOT NULL')},
 {key:'admin',label:'Administrador da empresa',complete:await count("SELECT count(*) n FROM memberships WHERE company_id=$1 AND role='company_admin' AND active")},
 {key:'condo',label:'Condomínio cadastrado',complete:await count('SELECT count(*) n FROM condos WHERE company_id=$1')},
 {key:'equipment',label:'Equipamento homologado',complete:await count("SELECT count(*) n FROM records WHERE company_id=$1 AND kind='devices' AND data->>'homologated'='true'")},
 {key:'users',label:'Morador vinculado',complete:await count("SELECT count(*) n FROM memberships WHERE company_id=$1 AND role='resident' AND active")}
];}
