import { Controller,Get,Post,Param,Body,Req,ForbiddenException,NotFoundException,ServiceUnavailableException,ConflictException } from '@nestjs/common';
import { ApiTags,ApiBearerAuth } from '@nestjs/swagger';
import type { Request } from 'express';
import { SignJWT,jwtVerify } from 'jose';
import { z } from 'zod';
import { createHash } from 'node:crypto';
import { tenant,agent,secret } from './controller';
import { core,db,env } from './runtime';
import { admins,operators } from './core';
import { requireRole,seal,unseal } from './security';
import { one,type Scope } from './db';
import { uuid } from './schemas';
const mediaKey=()=>createHash('sha256').update(`${env.DATA_KEY}:media-v1`).digest();
@ApiTags('Integrações') @ApiBearerAuth() @Controller('v1')
export class IntegrationController {
 @Post('whatsapp/connect') connect(@Req()req:Request){return tenant(req,async(q,s)=>{requireRole(s,admins);await core.event(q,s,'whatsapp.pair_requested');return bridge(s.company!,'connect');});}
 @Get('whatsapp/session') session(@Req()req:Request){return tenant(req,async(q,s)=>{requireRole(s,admins);return bridge(s.company!,'status','GET');});}
 @Post('whatsapp/disconnect') disconnect(@Req()req:Request){return tenant(req,async(q,s)=>{requireRole(s,admins);await core.event(q,s,'whatsapp.disconnected');return bridge(s.company!,'disconnect');});}
 @Post('whatsapp/send') sendWhatsApp(@Req()req:Request,@Body()body:any){const b=z.object({to:z.string().regex(/^\+[1-9]\d{7,14}$/),text:z.string().trim().min(1).max(2000),request_key:z.string().regex(/^[A-Za-z0-9:_-]{16,128}$/)}).strict().parse(body);return tenant(req,async(q,s)=>{requireRole(s,[...admins,'supervisor']);await core.active(q,s);const result=await bridge(s.company!,'send','POST',b);await core.event(q,s,'whatsapp.message_sent',undefined,undefined,{to:b.to.replace(/.(?=.{4})/g,'*'),request_key:b.request_key});return result;});}
 @Post('internal/whatsapp/send') sendWhatsAppInternal(@Req()req:Request,@Body()body:any){secret(req.headers['x-service-key'] as string,env.INTERNAL_KEY);const b=z.object({company_id:uuid,to:z.string().regex(/^\+[1-9]\d{7,14}$/),text:z.string().trim().min(1).max(2000),request_key:z.string().regex(/^[A-Za-z0-9:_-]{16,128}$/)}).strict().parse(body);return bridge(b.company_id,'send','POST',{to:b.to,text:b.text,request_key:b.request_key});}
 @Post('agent/credentials/pending') pending(@Req()req:Request){return agent(req,q=>q.query("SELECT id,data FROM records WHERE kind='credentials' AND data->>'status' IN ('pending','revocation_pending') ORDER BY updated_at LIMIT 50").then(r=>r.rows));}
 @Post('agent/credentials/:id/ack') credentialAck(@Req()req:Request,@Param('id')id:string,@Body()body:any){const state=z.enum(['active','revoked']).parse(body.state);return agent(req,async(q,s)=>{const c=await core.record(q,uuid.parse(id),'credentials');const expected=state==='active'?'pending':'revocation_pending';if(c.data.status!==expected)throw new ConflictException('Sincronização já concluída ou alterada.');await q.query("UPDATE records SET data=jsonb_set(data,'{status}',to_jsonb($1::text)),updated_at=now() WHERE id=$2",[state,id]);await core.event(q,s,`credential.${state}`,id,c.condo_id,{},c.unit_id);return{state};});}
 @Post('cameras/:id/session') camera(@Req()req:Request,@Param('id')id:string){return tenant(req,async(q,s)=>{requireRole(s,operators);await core.active(q,s);if(!env.MEDIA_PUBLIC_URL)throw new ServiceUnavailableException('Servidor de vídeo ainda não configurado.');const c=await core.record(q,uuid.parse(id),'cameras');const path=`${s.company}/${c.data.stream_path}`;const token=await new SignJWT({company:s.company,condo:c.condo_id,camera:c.id,path,role:s.role}).setProtectedHeader({alg:'HS256'}).setSubject(s.subject).setAudience('portaria-media').setIssuedAt().setExpirationTime('60s').sign(mediaKey());await core.event(q,s,'camera.viewed',c.id,c.condo_id);return{url:`${env.MEDIA_PUBLIC_URL}/${path}/whep`,token,expires_in:60};});}
 @Post('internal/media/auth') async mediaAuth(@Body()body:any){const b=z.object({token:z.string(),path:z.string(),action:z.string()}).passthrough().parse(body);if(b.action!=='read')throw new ForbiddenException();let p;try{p=(await jwtVerify(b.token,mediaKey(),{audience:'portaria-media',algorithms:['HS256']})).payload;}catch{throw new ForbiddenException();}if(p.path!==b.path||!p.sub)throw new ForbiddenException();return db.transaction({subject:p.sub,company:String(p.company),role:String(p.role),condos:[String(p.condo)]},async q=>{const c=await one(q,'SELECT status FROM companies WHERE id=$1',[p.company]);if(c?.status!=='active')throw new ForbiddenException();if(p.role==='support'){const grant=await one(q,'SELECT app.support_active($1,$2) AS active',[p.company,p.sub]);if(!grant?.active)throw new ForbiddenException();}else{const m=await one(q,'SELECT role,condo_ids FROM memberships WHERE subject=$1 AND company_id=$2 AND active',[p.sub,p.company]);if(!m||!operators.includes(m.role)||m.role!=='company_admin'&&!m.condo_ids.includes(p.condo))throw new ForbiddenException();}return{authorized:true};});}
 @Get('telephony/account') phone(@Req()req:Request){return tenant(req,async(q,s)=>{requireRole(s,operators);await core.active(q,s);if(!env.SIP_WEBSOCKET_URL||!env.SIP_DOMAIN)throw new ServiceUnavailableException('Interfonia não configurada.');const account=await one(q,'SELECT * FROM sip_accounts WHERE subject=$1 AND active',[s.subject]);if(!account)throw new NotFoundException('Sua conta de interfonia ainda não foi provisionada.');return{username:account.username,password:unseal(account.password_cipher,env.DATA_KEY!),server:env.SIP_WEBSOCKET_URL,domain:env.SIP_DOMAIN};});}
 @Post('telephony/accounts') phoneAccount(@Req()req:Request,@Body()body:any){const b=z.object({subject:z.string().min(1),username:z.string().regex(/^[a-zA-Z0-9_-]{3,100}$/),password:z.string().min(20).max(200)}).strict().parse(body);return tenant(req,async(q,s)=>{requireRole(s,admins);const m=await one(q,'SELECT * FROM memberships WHERE subject=$1 AND company_id=$2 AND active',[b.subject,s.company]);if(!m||!operators.includes(m.role))throw new ForbiddenException('Vincule um operador ativo antes de configurar a interfonia.');await q.query('INSERT INTO sip_accounts(company_id,subject,username,password_cipher) VALUES($1,$2,$3,$4) ON CONFLICT(company_id,subject) DO UPDATE SET username=$3,password_cipher=$4,active=true',[s.company,b.subject,b.username,seal(b.password,env.DATA_KEY!)]);await core.event(q,s,'telephony.account_configured',undefined,undefined,{subject:b.subject});return{configured:true};});}
 @Get('calls') calls(@Req()req:Request){return tenant(req,async(q,s)=>{requireRole(s,operators);return(await q.query('SELECT * FROM call_events ORDER BY created_at DESC LIMIT 100')).rows;});}
 @Post('internal/telephony/events') callEvent(@Req()req:Request,@Body()body:any){secret(req.headers['x-service-key'] as string,env.INTERNAL_KEY);const b=z.object({company_id:uuid,condo_id:uuid,access_id:uuid,call_id:z.string().min(1).max(100),kind:z.enum(['ringing','answered','ended','missed'])}).strict().parse(body);const s:Scope={subject:'asterisk',company:b.company_id,role:'support'};return db.transaction(s,async q=>{await core.active(q,s);const a=await core.record(q,b.access_id,'access-points');if(a.condo_id!==b.condo_id)throw new ForbiddenException();const event=await one(q,'INSERT INTO call_events(company_id,condo_id,call_id,kind) VALUES($1,$2,$3,$4) ON CONFLICT(company_id,call_id,kind) DO NOTHING RETURNING id',[s.company,b.condo_id,b.call_id,b.kind]);if(!event)return{received:true};if(b.kind==='ringing')await q.query("INSERT INTO tickets(company_id,condo_id,access_id,title,call_id) VALUES($1,$2,$3,'Chamada de interfone',$4) ON CONFLICT(company_id,call_id) WHERE call_id IS NOT NULL DO NOTHING",[s.company,b.condo_id,b.access_id,b.call_id]);if(b.kind==='missed')await q.query("INSERT INTO records(company_id,condo_id,kind,data) VALUES($1,$2,'incidents',$3)",[s.company,b.condo_id,{name:'Chamada não atendida',description:`Chamada ${b.call_id}`,severity:'warning',status:'open'}]);await core.event(q,s,`call.${b.kind}`,event.id,b.condo_id,{call_id:b.call_id});return{received:true};});}
}
async function bridge(company:string,path:string,method='POST',body?:unknown){const bridges=JSON.parse(env.WHATSAPP_BRIDGES||'{}');const url=bridges[company];if(!url)throw new ServiceUnavailableException('O serviço Whatsmeow desta empresa ainda não foi configurado.');const r=await fetch(`${url}/${path}`,{method,headers:{'X-Service-Key':env.WHATSAPP_KEY!,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});if(!r.ok)throw new ServiceUnavailableException('Não foi possível conectar o WhatsApp.');const result=await r.json() as any;if(result.company_id&&result.company_id!==company)throw new ForbiddenException('Integração vinculada a outra empresa.');return result;}
